"""
Settings Page - User settings.
"""

import streamlit as st
import json
from datetime import datetime

# Configuration
st.set_page_config(
    page_title="Open Pandas-AI - Settings",
    page_icon="⚙️",
    layout="wide"
)

from components.sidebar import render_minimal_sidebar
from components.llm_provider import render_llm_provider_selector
from core.session_manager import get_session_manager
from core.memory import SessionMemory

# Session
session = get_session_manager()
memory = SessionMemory()

# Sidebar
render_minimal_sidebar()

# Header
st.title("⚙️ Settings")

st.markdown("---")

# Tabs
tab1, tab2, tab3, tab4, tab5 = st.tabs(["⚙️ Preferences", "LLM Provider", "🧠 Memory", "📊 Session", "ℹ️ About"])

# Tab 1: Preferences
with tab1:
    st.markdown("### 👤 User Preferences")
    
    col1, col2 = st.columns(2)
    
    with col1:
        st.markdown("#### Display Mode")
        
        user_level = st.radio(
            "User Level",
            options=['expert', 'beginner'],
            index=0 if session.user_level == 'expert' else 1,
            format_func=lambda x: "🎓 Expert - All options" if x == 'expert' else "🌱 Beginner - Simplified interface",
            horizontal=True
        )
        if user_level != session.user_level:
            session.set_user_level(user_level)
            st.success(f"Mode changed to: {user_level}")
        
        st.markdown("---")
        
        language = st.selectbox(
            "🌐 Language",
            options=['fr', 'en'],
            index=0 if session.language == 'fr' else 1,
            format_func=lambda x: "🇫🇷 Français" if x == 'fr' else "🇬🇧 English"
        )
        if language != session.language:
            session.set_language(language)
            st.success(f"Language changed to: {language}")
    
    with col2:
        st.markdown("#### Code Display")
        
        show_code = st.checkbox(
            "Show generated Python code",
            value=session.show_code,
            help="Shows the code generated by AI for each question"
        )
        if show_code != session.show_code:
            session.set_show_code(show_code)
            st.success("Preference updated")
        
        st.markdown("---")
        
        st.markdown("#### Theme")
        st.info("Theme is managed by Streamlit. Go to Settings > Theme in the menu (☰)")

# Tab 2: LLM Provider
with tab2:
    render_llm_provider_selector(title="LLM Provider")

# Tab 3: Memory
with tab3:
    st.markdown("### 🧠 Memory Management")
    
    messages = memory.get_all()
    
    col1, col2 = st.columns([2, 1])
    
    with col1:
        st.metric("Messages in memory", len(messages))
        
        if messages:
            st.markdown("#### Context Preview")
            with st.expander("View messages", expanded=False):
                for msg in messages:
                    role = msg.get('role', 'unknown')
                    content = msg.get('content', '')
                    timestamp = msg.get('timestamp', '')
                    
                    icon = "👤" if role == 'user' else "🤖"
                    st.markdown(f"**{icon} {role}** {f'• {timestamp}' if timestamp else ''}")
                    st.markdown(f"> {content[:200]}{'...' if len(content) > 200 else ''}")
                    st.markdown("---")
    
    with col2:
        st.markdown("#### Actions")
        
        if st.button("🗑️ Clear Memory", use_container_width=True, type="secondary"):
            memory.clear()
            st.success("Memory cleared")
            st.rerun()
        
        st.markdown("---")
        
        # Export
        st.markdown("#### Export/Import")
        
        export_data = json.dumps(memory.export(), ensure_ascii=False, indent=2)
        st.download_button(
            "💾 Export Memory",
            data=export_data,
            file_name=f"memory_export_{datetime.now().strftime('%Y%m%d_%H%M%S')}.json",
            mime="application/json",
            use_container_width=True
        )
        
        uploaded = st.file_uploader("📂 Import Memory", type=['json'], key="settings_memory_import")
        if uploaded:
            try:
                imported = json.load(uploaded)
                memory.import_history(imported)
                st.success("Memory imported successfully")
                st.rerun()
            except Exception as e:
                st.error(f"Import error: {e}")

# Tab 4: Session
with tab4:
    st.markdown("### 📊 Session Information")
    
    metrics = session.get_session_metrics()
    
    col1, col2, col3 = st.columns(3)
    
    with col1:
        st.markdown("#### Identity")
        st.code(f"Session ID: {session.session_id}")
        st.metric("Duration", f"{metrics['duration_minutes']} minutes")
    
    with col2:
        st.markdown("#### Activity")
        st.metric("Exchanges", metrics['exchange_count'])
        st.metric("Data Loaded", "Yes" if metrics['has_data'] else "No")
    
    with col3:
        st.markdown("#### Data")
        if metrics['has_data']:
            st.info(f"📁 {metrics['data_name'] or 'DataFrame'}")
            if metrics['quality_score']:
                st.metric("Quality", f"{metrics['quality_score']:.0f}/100")
        else:
            st.warning("No data")
    
    st.markdown("---")
    
    st.markdown("#### Session Actions")
    
    col1, col2 = st.columns(2)
    
    with col1:
        if st.button("🗑️ Reset Data", use_container_width=True):
            session.reset_data()
            st.success("Data reset")
            st.rerun()
    
    with col2:
        if st.button("⚠️ Reset Complete Session", use_container_width=True, type="secondary"):
            if st.checkbox("I confirm I want to reset everything"):
                session.reset_session()
                memory.clear()
                st.success("Session reset")
                st.rerun()

# Tab 5: About
with tab5:
    st.markdown("### ℹ️ About Open Pandas-AI")
    
    st.markdown("""
    **Open Pandas-AI** est un agent d'analyse de données intelligent qui permet 
    d'interroger vos fichiers CSV et Excel en langage naturel.
    
    #### 🛠️ Technologies utilisées
    
    | Composant | Technologie |
    |-----------|-------------|
    | Frontend | Streamlit |
    | LLM | Codestral (Mistral AI) |
    | Data Processing | Pandas |
    | Base de données | PostgreSQL / SQLite |
    | Exécution sécurisée | Docker Sandbox |
    
    #### 🔒 Sécurité
    
    - Exécution du code dans un environnement sandboxé
    - Analyse AST du code généré
    - Blocage des opérations dangereuses
    - Pas d'accès réseau dans le sandbox
    
    #### 🎯 Fonctionnalités principales
    
    - ✅ Analyse de données en langage naturel
    - ✅ Support multi-fichiers (CSV, Excel)
    - ✅ Support multi-feuilles Excel
    - ✅ Tableaux croisés dynamiques
    - ✅ Génération de graphiques
    - ✅ Export Excel formaté
    - ✅ Détection d'anomalies
    - ✅ Mémoire contextuelle
    - ✅ Analyse professionnelle des résultats
    
    #### 📝 Licence
    
    Open source - MIT License
    
    ---
    
    *Version 2.0 - Refonte Frontend Multi-Pages*
    """)
    
    # API Status
    st.markdown("---")
    st.markdown("#### 🔌 Statut API")
    
    try:
        from core.llm import call_llm
        st.success("✅ API Mistral AI connectée")
    except Exception as e:
        st.error(f"❌ Erreur API: {e}")

# Navigation
st.markdown("---")
col1, col2 = st.columns(2)
with col1:
    if st.button("🏠 Accueil", use_container_width=True):
        st.switch_page("pages/1_🏠_Home.py")
with col2:
    if st.button("🤖 Agent IA", use_container_width=True, type="primary"):
        st.switch_page("pages/3_🤖_Agent.py")
